const BLOG_POST_1_I =
    "https://images.unsplash.com/photo-1515705576963-95cad62945b6?q=80&force=true&w=1920";
const BLOG_POST_1_H = "LinkedIn Introduction - Friday 29th August 2025";
const BLOG_POST_1_P =
    "Hi there LinkedIn! I figured it would be a good time for a reintroduction so you get to know me better and my career ambitions. My name is Thomas Popham (he/him) and I’m a postgraduate in MSc. Computer Science (June 2023) from Teesside University. I’d best describe myself as eager, curious and deeply supportive of other graduates like myself; looking to make their mark within software development. Following my experience during university, I have since developed academic and personal experience in technologies such as: Android/Flutter/some React Native front-end/mobile app development, .NET/Node.JS for back-end development, database management with SQL/PostgreSQL/MongoDB/Google Firestore, as well as some Unreal Engine/Blender experience for 3D Animation Rigging. I firmly believe that life-long learning is one of my main driving forces for my career; spurring me to develop my skillset and experience in areas of technology I’m most passionate about. Recently, I have been improving my knowledge and experience within full-stack development and animation development in line with my passion for supporting children in their educational journey. My ultimate career goal is to develop educational games/immersive software for young children based on impactful academic research and to make a meaningful positive difference to their educational development and pedagogy. I’ve looked into existing research into the effective adoption of technology (e.g. Augmented Reality or Artificial Intelligence) for neurodiverse individuals and how it can be effective in supporting children with Autism or Autism with ADHD. In my spare time, I’m passionate for literature (currently reading Piranesi by Susanna Clarke), watching movies (especially the Studio Ghibli films), listening to music (ELO, Rush and David Bowie are my favourites) and some creative drawing/animation. I firmly believe that creativity is a critical driving force for a child’s lifelong development and forms my overall approach to problem solving, project planning and software design and development. Enabling me to \"think-outside-the-box\" and share a research-based perspective that I would love to bring to the workplace. If you need any technical support or you wish to give any career advice with me, please feel free to share! I’m more than happy to connect with other developers (especially other computer graduates like myself!) and to share knowledge, experience and advice through LinkedIn. Over the next few months, I will be sharing updates on personal projects I will be actively working on along with any technical support I could share with other graduates like myself. You're also more than welcome to reshare this post with your network! It’s great meeting you all and I look forward to connecting with you! Thanks!";

const BLOG_POST_2_I = "https://images.unsplash.com/photo-1460518451285-97b6aa326961?q=80&force=true&w=1920";
const BLOG_POST_2_H = "Project Update - dreamStudy - Tuesday 17th March 2026";
const BLOG_POST_2_P = "Hey there LinkedIn! Thought I might share some of what I’ve been working on lately (keep in mind, it's VERY early in development!) with you all. I’ve been lately been inspired by the work done by Genio and Arbor Education and how they’ve supported students in their educational development and gave teachers the tools to best support them. My full-stack project (called dreamStudy) is being built specifically for SEND (Special Educational Needs and Disabilities) students who are taking their GCSE and A Level examinations and to best support their revision. I plan to do this through the incorporation of key accessibility tools like an built-in AAC, filters for colour-blind support, dyslexia-friendly text fonts and hand gesture control that can best support their learning. I firmly believe that NO child or young person should ever be left behind in their learning purely because of their disability or needs and this project that I am currently building aims to achieve this. I also wanted to use this project as an opportunity to further develop my skills within React Native as my main front-end framework of choice for both web (yes web!) and mobile devices. I’ve also looked into incorporating Skia as a powerful graphical renderer that can display modern and performant UI components that enhance the user’s overall experience with the website or app. You might have heard of Skia used as the main renderer for Flutter (before it was replaced by Impeller), but thanks to Shopify, it has been reincorporated to work with React Native. This makes it an ideal library for rendering graphics and animations, making it much more performant for an app where 60fps performance is key in certain UX cases! Any React Native developers, SEND teachers and experts in the field are more than welcome to share feedback with me on where key improvements and recommendations should be made to the development of the project: https://lnkd.in/eHqgM2x5. I'll be sharing more (when I have time) on any other projects that I will be working on. Thank you very much! 😀👍 一緒に夢に飛び込みましょう (Let’s dive into our dreams together)";

