
// Hero tags for the HomeScreen
const HOME_HERO_TAG_1 = "HOME_HERO_TAG_1";
const HOME_HERO_TAG_2 = "HOME_HERO_TAG_2";
const HOME_HERO_TAG_3 = "HOME_HERO_TAG_3";

// Hero tags for the ProjectsScreen
const PROJECTS_HERO_TAG_1 = "PROJECTS_HERO_TAG_1";
const PROJECTS_HERO_TAG_2 = "PROJECTS_HERO_TAG_2";
const PROJECTS_HERO_TAG_3 = "PROJECTS_HERO_TAG_3";
const PROJECTS_HERO_TAG_4 = "PROJECTS_HERO_TAG_4";

// Hero tags for the ExperienceScreen
const EXPERIENCE_HERO_TAG_1 = "EXPERIENCE_HERO_TAG_1";
const EXPERIENCE_HERO_TAG_2 = "EXPERIENCE_HERO_TAG_2";
const EXPERIENCE_HERO_TAG_3 = "EXPERIENCE_HERO_TAG_3";
const EXPERIENCE_HERO_TAG_4 = "EXPERIENCE_HERO_TAG_4";
const EXPERIENCE_HERO_TAG_5 = "EXPERIENCE_HERO_TAG_5";
const EXPERIENCE_HERO_TAG_6 = "EXPERIENCE_HERO_TAG_6";
const EXPERIENCE_HERO_TAG_7 = "EXPERIENCE_HERO_TAG_7";
const EXPERIENCE_HERO_TAG_8 = "EXPERIENCE_HERO_TAG_8";


// Hero tags for the BlogScreen
const BLOG_HERO_TAG_1 = "BLOG_POST_1";





